### ISSUE TITLE
can't get ip after replugin

### ISSUE THREAD

**Issue by meikeeit** [Mieze/RealtekRTL8100#3]
can't get an ip address after replugin,rtl8106e,but version 1.0.0 is alright.

**Comment by Mieze** [comment]
Due to the lack of hardware to run tests, there is almost nothing I can do for you because I have no idea where to start searching for a solution. Sorry!

**Comment by meikeeit** [comment]
alright，thanks for your work，I can use 1.0.0,it's fine.

**Comment by lioliy** [comment]
Me too I will get kernel panic and reboot if I run this command when replugging.
`sudo ifconfig en0 down`
But you can run that command when unplugged.
After running, then run `sudo ifconfig en0 up`
You can plug again and it will working. You CAN get a IP address.

**Comment by meikeeit** [comment]
> Me too I will get kernel panic and reboot if I run this command when replugging.
> `sudo ifconfig en0 down`
> But you can run that command when unplugged.
> After running, then run `sudo ifconfig en0 up`
> You can plug again and it will working. You CAN get a IP address.

Thanks,but I'm using the first version,and it works fine on Mojave as well,you should have a try😊.
