### ISSUE TITLE
Not working after repluging

### ISSUE THREAD

**Issue by davidyuk** [Mieze/RealtekRTL8100#4]
I think I have the same issue as in #3 and this thread: https://www.tonymacx86.com/threads/solved-issue-with-realtekrtl8100-kext.241496/.

I have macOS Mojave 10.14.5 installed on HP Pavilion 15-p171nr. RealtekRTL8100.kext used with RTL8101/2/6E controller ([the whole lspci output](https://pastebin.com/ur7cnp9L)). 

Initially, it works fine. After unplugging/plugging in networks ethernet connection status is "Not Connected" and after some time it becomes "Connected", but with self-assigned IP instead of one provided by DHCP server.

The workaround proposed in #3 (running `sudo ifconfig en0 down`/`up`) works.

ifconfig output before unplugging:
```
$ ifconfig
lo0: flags=8049<UP,LOOPBACK,RUNNING,MULTICAST> mtu 16384
	options=1203<RXCSUM,TXCSUM,TXSTATUS,SW_TIMESTAMP>
	inet 127.0.0.1 netmask 0xff000000 
	inet6 ::1 prefixlen 128 
	inet6 fe80::1%lo0 prefixlen 64 scopeid 0x1 
	nd6 options=201<PERFORMNUD,DAD>
gif0: flags=8010<POINTOPOINT,MULTICAST> mtu 1280
stf0: flags=0<> mtu 1280
XHC20: flags=0<> mtu 0
EHC29: flags=0<> mtu 0
en0: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500
	options=6b<RXCSUM,TXCSUM,VLAN_HWTAGGING,TSO4,TSO6>
	ether 8c:dc:d4:7f:67:94 
	inet6 fe80::802:8d00:474f:a3df%en0 prefixlen 64 secured scopeid 0x6 
	inet 192.168.1.53 netmask 0xffffff00 broadcast 192.168.1.255
	nd6 options=201<PERFORMNUD,DAD>
	media: autoselect (100baseTX <full-duplex>)
	status: active
utun0: flags=8051<UP,POINTOPOINT,RUNNING,MULTICAST> mtu 2000
	inet6 fe80::cdf:9806:5b36:9869%utun0 prefixlen 64 scopeid 0x7 
	nd6 options=201<PERFORMNUD,DAD>
```
after unpluging:
```
$ ifconfig
lo0: flags=8049<UP,LOOPBACK,RUNNING,MULTICAST> mtu 16384
	options=1203<RXCSUM,TXCSUM,TXSTATUS,SW_TIMESTAMP>
	inet 127.0.0.1 netmask 0xff000000 
	inet6 ::1 prefixlen 128 
	inet6 fe80::1%lo0 prefixlen 64 scopeid 0x1 
	nd6 options=201<PERFORMNUD,DAD>
gif0: flags=8010<POINTOPOINT,MULTICAST> mtu 1280
stf0: flags=0<> mtu 1280
XHC20: flags=0<> mtu 0
EHC29: flags=0<> mtu 0
en0: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500
	options=6b<RXCSUM,TXCSUM,VLAN_HWTAGGING,TSO4,TSO6>
	ether 8c:dc:d4:7f:67:94 
	inet6 fe80::802:8d00:474f:a3df%en0 prefixlen 64 secured scopeid 0x6 
	nd6 options=201<PERFORMNUD,DAD>
	media: autoselect (100baseTX <full-duplex>)
	status: active
utun0: flags=8051<UP,POINTOPOINT,RUNNING,MULTICAST> mtu 2000
	inet6 fe80::cdf:9806:5b36:9869%utun0 prefixlen 64 scopeid 0x7 
	nd6 options=201<PERFORMNUD,DAD>
```

**Comment by Mieze** [comment]
As I don't have any hardware to test, there is nothing I can do for you. Sorry!

**Comment by lordofpc734** [comment]
> As I don't have any hardware to test, there is nothing I can do for you. Sorry!

I found one that is based off of yours but it won't properly work on mojave (its too slow)

[okaishRealtekRTL8100.kext.zip](https://github.com/Mieze/RealtekRTL8100/files/3433452/okaishRealtekRTL8100.kext.zip)

**Comment by Resunny** [comment]
> > As I don't have any hardware to test, there is nothing I can do for you. Sorry!
> 
> I found one that is based off of yours. it does not have that issue mentioned above. but it won't properly work on mojave (its too slow)
> 
> [okaishRealtekRTL8100.kext.zip](https://github.com/Mieze/RealtekRTL8100/files/3433452/okaishRealtekRTL8100.kext.zip)

Hello there!

I used okaishRealtekRTL8100.kext you provided.
I did not find the problem you mentioned above, the Internet speed is normal.
The system I am using is macOS Catalina 10.15.1.

I want to ask, do you have the source code for this kext? The version of this kext is a bit low, and I want to try to add it and fix the kext of Mieze,

Thank you!

**Comment by errorexists** [comment]
> [okaishRealtekRTL8100.kext.zip](https://github.com/Mieze/RealtekRTL8100/files/3433452/okaishRealtekRTL8100.kext.zip)

is there a source for this one as it seems to work for me but not the one in this repo 
thank you

**Comment by lordofpc734** [comment]
no, I just found that kext on some random page of tonymac forums, I did not find any source code for it.
Right now im using the newest release of RTL8100. the issue still exists, but i've learned to live with it, after unplugging, i run the command "sudo ifconfig en0 down, sudo ifconfig en0 up". that fixes the issue and ethernet works again

**Comment by errorexists** [comment]
ok, pavo had a look at the source for this one here from the repo made some edits to it an is working on my laptop, here if like to try it 
[RealtekRTL8100.kext.zip](https://github.com/Mieze/RealtekRTL8100/files/4908527/RealtekRTL8100.kext.zip)

**Comment by lordofpc734** [comment]
> ok, pavo had a look at the source for this one here from the repo made some edits to it an is working on my laptop, here if like to try it
> [RealtekRTL8100.kext.zip](https://github.com/Mieze/RealtekRTL8100/files/4908527/RealtekRTL8100.kext.zip)

hmm, thanks. I tried it but It didn't work, macOS couldn't see my ethernet at all
I checked KEXTSTAT and for some reason, it wasn't loaded, so I also tried with Clover. (before that, I used OC with ProperTree's OC snapshot) 
here is the output of ifconfig if it helps
![Screen Shot 1399-04-22 at 7 29 11 PM](https://user-images.githubusercontent.com/53150594/87250183-779b2f80-c478-11ea-9975-9bead7fe1db9.png)
Glad that it works on your system though,

**Comment by davidyuk** [comment]
Closing issues without resolving makes it more difficult to track them.

**Comment by Mieze** [comment]
If somebody with programming skills and appropriate hardware to test is willing to work on this issue or comes up with a patch, I'll be happy to integrate it but this discussion here leads us nowhere, so that I decided close the issue.

**Comment by Mateo1234454545** [comment]
With this kext I'm getting 1.40-1.50pkg at idle, while with okaishRealtekRTL8100.kext pkg is 0.80-0.90.
